import "./diggingRobot"
import "./dummyBlock"
import "./polishCow"
import "./koprium/Amplifier"
import "./koprium/Meteorite"
import "./koprium/Pylon"
import "./koprium/dummySpawn"
import "./koprium/loottable"