import "./diggingRobot"
import "./dummyBlock"
import "./polishCow"
import "./nyanCat"

import "./koprium/Amplifier"
import "./koprium/Meteorite"
import "./koprium/Pylon"
import "./koprium/dummySpawn"
import "./koprium/loottable"
import "./kopriumDagger"
import "./koprium/mortar"
import "./kopriumCannonBall"